import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from './header'
import title from '../styles/Title.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Site kit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Header></Header>

        <h1 className={title.title}>About</h1>
        <p className={title.subtitle}>This is a small peice of text all about me.</p>

    </div>
  )
}