import Head from 'next/head'
import Image from 'next/image'
import Header from './header'
import title from '../styles/Title.module.css'
import styles from '../styles/Contact.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Site kit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Header></Header>

      <main className={styles.main}>
        <h1 className={title.title}>
        Contact
        </h1>

        <p className={title.subtitle}>
          Like my work or just want to chat? Let's get in contact.
        </p>

        <div className={styles.email}>
            <a href="mailto:mail.toby@icloud.com">
                <h1 className={styles.mail}>Email</h1>
                <p className={styles.mailDescription}>Email is the perfect way to get in contact. So, here's mine.</p>
            </a>
        </div>

        <div className={styles.discord}>
            <p className={styles.discordUsername}>Toby_#8552</p>
                <h1 className={styles.discordName}>Discord</h1>
                <p className={styles.discordDescription}>Discord is another amazing platform to contact people on.</p>
        </div>

        <div className={styles.twitter}>
            <p className={styles.twitterUsername}>@DevelopedByToby</p>
                <h1 className={styles.twitterName}>Twitter</h1>
                <p className={styles.twitterDescription}>This is just a placeholder, my DMs aren't actually open. You can follow me though!</p>
        </div>

        </main>
    </div>
  )
}
