import type { NextPage } from "next"
import Head from "next/head"
import Link from "next/link"

const Home: NextPage = () => {
  return (
    <div className="grid mt-32 place-items-center space-y-4">
      <Head>
        <title>Next.js App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-6xl font-bold">Hello from Next.js!</h1>
      <h2>Next.js, TypeScript and Tailwind.</h2>
      <Link
        href="https://github.com/developedbytoby/nextjs-ts-tailwind-starter#developedbytobynextjs-ts-tailwind-starter"
      >
        Check this out if you need a hand
      </Link>
    </div>
  )
}

export default Home
