import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from './header'

/* Hey there! Welcome to conifer. Notes like these are all over the place.
 Their purpose is to try and help you with your project as much as possible!
 */

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Welcome to conifer!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/conifer.png" />
      </Head>
        <Header></Header>

      <main className={styles.main}>
        <h1 className={styles.title}>
        Welcome to conifer!
        </h1>

    <div className={styles.imageContainer}>
           {/*  Want to replace this image? Make sure that image is in the public folder, 
         and then simply write /IMAGE-NAME.png in where it says src!  */}
      <Image src="/conifer.png" alt="Evergreen tree" width="100%" height="100%" layout="responsive" objectFit="contain" />
    </div>

        <p className={styles.description}>
          Navigate to <code>pages/index.js</code> to edit this page.
        </p>
        <p className={styles.help}>Need a hand? Check out <a href="https://conifer-docs.notion.site/60bf9d62f5924a32a0a67ca7f25b124a?v=2fd3563198484fb1a94f218a8ffec31b">the docs</a>.</p>
        
        </main>
    </div>
  )
}
