import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Site kit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
        Wolfgang Mozart
        </h1>

        <p className={styles.description}>
          Music composer.
        </p>

        <div className={styles.links}>
          <p>
          <a href="/about">About</a> ∙ &nbsp;
          <a href="/projects">Projects</a> ∙ &nbsp;
          <a href="/contact">Contact</a>
          </p>
        </div>

          <div className={styles.imageContainer}>
          <Image className={styles.me} src="/mozart.jpeg" alt="This is me." width="100%" height="100%" layout="responsive" objectFit="contain" />
        </div>
        
        </main>
    </div>
  )
}
