import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Projects.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Site kit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <h1 className={styles.title}>Projects</h1>
    <p className={styles.subtitle}>I have worked on quite a lot of projects in my lifetime.</p>
    </div>
  )
}
