import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Projects.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Projects</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body>

    <h1 className={styles.title}>Projects</h1>
    <p className={styles.subtitle}>I've worked on a few different projects before- here's a list of some of my favourites.</p>
    </body>
    </div>
  )
}
