import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Projects.module.css'
import title from '../styles/Title.module.css'
import Header from './header'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Projects</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body>
        <Header></Header>

    <h1 className={title.title}>Projects</h1>
    <p className={title.subtitle}>I've worked on a few different projects before- here's a list of some of my favourites.</p>
    </body>
    </div>
  )
}
